/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button/Button.vue')['default']
    ButtonButton: typeof import('./components/Button/Button.vue')['default']
    Icon: typeof import('./components/Icon/Icon.vue')['default']
    IconIcon: typeof import('./components/Icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
